---
language: ruby
rvm:
  - 2.3.6
  - 2.5.0

addons:
  apt:
    sources:  [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
    packages: [ 'g++-5', 'clang-3.8','libc++-dev', 'libc++abi-dev', 'gperf']

before_install:
  - bash -x ./travis.sh

before_script: './travis.sh'
