---
language: ruby
rvm:
  - 2.3.6
  - 2.5.0

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
          sources: *sources

before_install:
  - sudo apt-get install -y gperf cmake openssl
  - bash -x ./travis.sh

before_script: './travis.sh'
