---
language: ruby
rvm:
  - 2.3.6
  - 2.5.0

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

before_install:
  - sudo apt-get install -y gperf cmake openssl
  - bash -x ./travis.sh

before_script: './travis.sh'
